function [I,J,deg,m,n,r,TI,TJ,NI,NJ] = QT_Preprocessing(G,c)
[I,J,~] = find(triu(G)); 
deg = sum(G,2); 
m = length(I); 
n = size(G,1); 
r = size(c{1},1); 
aa = (1:r^2)';
AA = reshape(aa,r,r);
A = kron(AA,eye(r));
[II,JJ,b] = find(A);
[~,id] = sort(b,'ascend');
II = II(id);
JJ = JJ(id);
TJ = (JJ-1)*r^2+II;
A = kron(eye(r),AA);
[II,JJ,b] = find(A);
[~,id] = sort(b,'ascend');
II = II(id);
JJ = JJ(id);
TI = (JJ-1)*r^2+II;
NI = cell(1,n); 
NJ = cell(1,n); 
for k = 1:m
    i = I(k);
    j = J(k);
    NI{i} = [NI{i},k];
    NJ{j} = [NJ{j},k];
end